name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: ./.github/workflows/templates/lint-job.yml
  typecheck:
    uses: ./.github/workflows/templates/typecheck-job.yml
  test:
    needs: [lint, typecheck]
    uses: ./.github/workflows/templates/test-job.yml